apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: idamerete/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        infer:
          - "src/**/*.ts"
    - image: idamerete/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        infer:
          - "**/*.js"
    - image: idamerete/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        infer:
          - "src/**/*.ts"
